repos:
  - repo: https://github.com/dbt-checkpoint/dbt-checkpoint
    rev: v2.0.8
    hooks:
      - id: dbt-deps
        args: [ "--cmd-flags", "++project-dir", "dbt_project", "++profiles-dir", "dbt_project" ]
      - id: dbt-parse
        args: [ "--cmd-flags", "++project-dir", "dbt_project", "++target", "dev", "++profiles-dir", "dbt_project" ]
      - id: check-model-has-properties-file
        args: [ "--manifest", "dbt_project/target/manifest.json" ]
        files: models
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 4.0.4
    hooks:
      - id: sqlfluff-lint
        args: ["--config", "dbt_project/.sqlfluff" ]
        files: "dbt_project"
      - id: sqlfluff-fix
        args: ["--config", "dbt_project/.sqlfluff" ]
        files: "dbt_project"
