{{ config(materialized='table') }}

with formatted_usage as (
    select
        mtx_container_name,
        event_id,
        msisdn,
        status_value,
        segment,
        calling_station_id,
        called_station_id,
        usage_quantity,
        rating_amount,
        cost_amount,
        cost_breakdown,
        role_of_node_name,
        service_classification,
        composite_usage_type,
        allowance_balance,
        allowance_balance_breakdown,
        gross_amount_after,
        gross_amount_after_breakdown,
        wallet_id,
        wallet_owner_external_id,
        wallet_owner_id,
        wallet_owner_type,
        unique_sequence_id,
        initiator_device_external_id,
        initiator_device_id,
        initiator_external_id,
        initiator_id,
        tax_code,
        idd_cc_name,
        idd_cc_region,
        origination_cc_name,
        origination_cc_region,
        date_format(start_date_time, 'yyyy-MM-dd HH:mm:ss') as start_date_time,
        date_format(end_date_time, 'yyyy-MM-dd HH:mm:ss') as end_date_time
    from {{ ref('intermediate_blugem_usage_combined') }}
)

select
    mtx_container_name,
    event_id,
    msisdn,
    status_value,
    segment,
    calling_station_id,
    called_station_id,
    start_date_time,
    end_date_time,
    usage_quantity,
    rating_amount,
    cost_amount,
    cost_breakdown,
    role_of_node_name,
    service_classification,
    composite_usage_type,
    allowance_balance,
    allowance_balance_breakdown,
    gross_amount_after,
    gross_amount_after_breakdown,
    wallet_id,
    wallet_owner_external_id,
    wallet_owner_id,
    wallet_owner_type,
    unique_sequence_id,
    initiator_device_external_id,
    initiator_device_id,
    initiator_external_id,
    initiator_id,
    tax_code,
    idd_cc_name,
    idd_cc_region,
    origination_cc_name,
    origination_cc_region
from formatted_usage
