{{ config(
  materialized = 'table'
) }}

with src as (
    select * from {{ source('tesco_finance_silver_schema', 'tap_store_sales_cleaned') }}
)

select
    src.invoice_id as transaction_number,
    'instore' as transaction_source,
    'missing mapping' as order_id,
    src.order_reference,
    'missing mapping' as location_id,
    'missing mapping' as order_number,
    'missing mapping' as dispatch_date,
    'missing mapping' as fulfilment_date,
    'missing mapping' as return_date,
    src.quantity as number_of_units,
    src.price_before_discounts_amount,
    src.price_after_discounts_amount,
    src.refund_amount,
    src.product_description as description,
    src.invoice_id,
    src.customer_id,
    src.tax_band,
    src.vat_amount,
    'missing mapping' as apportioned_earned_points,
    src.tpnb,
    src.subclass_code,
    src.subclass_name,
    src.brand,
    src.colleague_discount_amount,
    src.coupon_discount_amount,
    src.multi_saver_discount_amount,
    'missing mapping' as reduced_to_clear,
    src.price_cut_discount_amount,
    src.price_after_discounts_amount as net_amount,
    'missing mapping' as checked_out_date,
    'missing mapping' as promotion_value,
    'missing mapping' as price_cut,
    'missing mapping' as rtc,
    'missing mapping' as simple_promo,
    'missing mapping' as net_sales_sp,
    'missing mapping' as voucher_redeem,
    'missing mapping' as coupon_redeem,
    'missing mapping' as colleague_pct,
    'missing mapping' as clubcard_plus_pct,
    'missing mapping' as basket_promo,
    'missing mapping' as net_sales_bp,
    'missing mapping' as transaction_end_datetime,
    'missing mapping' as unit_of_measure,
    src.unique_product_key as product_id,
    src.gtin,
    src.tpna,
    src.tpnc,
    'missing mapping' as transaction_start_datetime,
    src.store_number as retail_outlet_number,
    'missing mapping' as debit_credit,
    'missing mapping' as multi_buy_promo_description,
    src.return_reason,
    src.store_format as store_format_code,
    'missing mapping' as store_format_description,
    src.checkout_number as checkout_no,
    'missing mapping' as clubcard_number,
    'missing mapping' as item_selling_price,
    src.unique_product_key as item_number,
    'missing mapping' as effective_pricing_date,
    'missing mapping' as quote_id,
    'missing mapping' as event_id,
    'missing mapping' as apportioned_burned_points,
    'missing mapping' as rtd,
    'missing mapping' as qualities,
    'missing mapping' as headline,
    src.transaction_date,
    src.transaction_date as created_date
from src
